LIST p=16F887
    #INCLUDE "P16F887.inc"
    RADIX HEX

    __CONFIG _CONFIG1, _FOSC_HS & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
    __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF

    DIST_CM     EQU 0x20
    UMBRAL_CM   EQU 0x21
    CICLO_CNT   EQU 0x22
    FLAGS       EQU 0x23
    TEMP        EQU 0x24
    TMR1_H      EQU 0x25
    TMR1_L      EQU 0x26
    CONT_DELAY  EQU 0x27
    TX_DEC      EQU 0x28
    TX_UNI      EQU 0x29
    ADC_RES     EQU 0x2A
    CONT_HI     EQU 0x2B
    UMBRAL_DEC  EQU 0x2C
    UMBRAL_UNI  EQU 0x2D
    DISP_SEL    EQU 0x2E
    PROD_H      EQU 0x2F
    PROD_L      EQU 0x30
    MULT_CNT    EQU 0x31
    QUOT        EQU 0x32
    BCD_TEMP    EQU 0x33   
    W_TEMP      EQU 0x70
    STATUS_TEMP EQU 0x71

    ORG 0x00
    GOTO INICIO

    ORG 0x04
    GOTO ISR

    ORG 0x05
    
TABLA
    ADDWF PCL,F
    RETLW b'00111111'     ;0
    RETLW b'00000110'     ;1
    RETLW b'01011011'     ;2
    RETLW b'01001111'     ;3
    RETLW b'01100110'     ;4
    RETLW b'01101101'     ;5
    RETLW b'01111101'     ;6
    RETLW b'00000111'     ;7
    RETLW b'01111111'     ;8
    RETLW b'01101111'     ;9

INICIO
    BANKSEL T1CON
    MOVLW b'00000001'
    MOVWF T1CON

    BANKSEL ADCON0
    MOVLW b'00000001'
    MOVWF ADCON0

    BANKSEL ADCON1
    MOVLW b'00000000'    
    MOVWF ADCON1

    BANKSEL RCSTA
    MOVLW b'10010000'
    MOVWF RCSTA

    BANKSEL SPBRG
    MOVLW .25
    MOVWF SPBRG
    BANKSEL TXSTA
    MOVLW b'00100100'
    MOVWF TXSTA

    BANKSEL OPTION_REG
    MOVLW b'00000101'
    MOVWF OPTION_REG

    BANKSEL TRISC
    BCF TRISC,0
    BSF TRISC,1
    BCF TRISC,6
    BSF TRISC,7
    BCF TRISC,2        ;RC2/CCP1 salida PWM

    BANKSEL TRISA
    BSF TRISA,0        ;RA0 entrada potenciometro

    BANKSEL TRISD
    CLRF TRISD           ;RD0-RD7 salidas (segmentos display)
    BANKSEL TRISE
    CLRF TRISE           ;RE0-RE1 salidas (selectores display)

    BANKSEL TRISB
    BSF TRISB,0        ;RB0 entrada boton emergencia
    BSF TRISB,1        ;RB1 entrada boton encendido
    BCF TRISB,2        ;RB2 salida LED motor encendido
    BCF TRISB,3        ;RB3 salida LED motor apagado
    BANKSEL WPUB
    BSF WPUB,0
    BSF WPUB,1

    BANKSEL PORTB
    BCF PORTB,2
    BSF PORTB,3

    BANKSEL ANSEL
    MOVLW b'00000001'     ;solo AN0 analogico
    MOVWF ANSEL
    BANKSEL ANSELH
    CLRF ANSELH

    BANKSEL PORTD
    CLRF PORTD
    BANKSEL PORTE
    CLRF PORTE

    ;configuracion PWM, arranca en 0% 
    BANKSEL PR2
    MOVLW .255
    MOVWF PR2

    BANKSEL CCPR1L
    CLRF CCPR1L

    BANKSEL CCP1CON
    CLRF CCP1CON

    BANKSEL PORTC
    BCF PORTC,2

    BANKSEL PIR1
    BCF PIR1,TMR2IF

    BANKSEL T2CON
    MOVLW b'00000111'     ;TMR2 ON, prescaler 1:16
    MOVWF T2CON

WAIT_TMR2_OVF
    BANKSEL PIR1
    BTFSS PIR1, TMR2IF
    GOTO WAIT_TMR2_OVF
    BCF PIR1, TMR2IF

    BANKSEL CCP1CON
    MOVLW b'00001100'     
    MOVWF CCP1CON

    BANKSEL DIST_CM
    CLRF DIST_CM
    CLRF ADC_RES
    MOVLW .10
    MOVWF UMBRAL_CM
    CLRF CICLO_CNT
    CLRF FLAGS          
    CLRF CONT_HI
    CLRF DISP_SEL
    MOVLW .1          
    MOVWF UMBRAL_DEC
    CLRF UMBRAL_UNI

    BCF PORTC,0

    MOVLW b'11110000'     ;GIE,PEIE,T0IE,INTE habilitadas
    MOVWF INTCON

    MOVLW .100
    MOVWF TMR0

LOOP
    GOTO LOOP

ISR
    MOVWF W_TEMP
    SWAPF STATUS,W
    MOVWF STATUS_TEMP

    BCF STATUS,RP0
    BCF STATUS,RP1

    BTFSS INTCON,INTF
    GOTO CHECK_T0IF
    CALL PARO_EMERGENCIA

CHECK_T0IF
    BTFSS INTCON,T0IF
    GOTO RECUPERAR_CONTEXTO

    MOVLW .100
    MOVWF TMR0
    BCF INTCON, T0IF

    CALL RUTINA_DISPLAY
    CALL RUTINA_CICLO
    CALL CHEQUEAR_BOTONES

RECUPERAR_CONTEXTO
    SWAPF STATUS_TEMP,W
    MOVWF STATUS
    SWAPF W_TEMP,F
    SWAPF W_TEMP,W
    RETFIE

APAGAR_MOTOR
    BANKSEL CCP1CON
    BCF CCP1CON,5
    BCF CCP1CON,4
    BANKSEL CCPR1L
    CLRF CCPR1L
    BANKSEL PORTB
    BCF PORTB,2
    BSF PORTB,3
    BANKSEL FLAGS
    BCF FLAGS,0
    RETURN
    
ENCENDER_MOTOR
    BANKSEL CCP1CON
    BSF CCP1CON,5
    BSF CCP1CON,4
    BANKSEL CCPR1L
    MOVLW .255
    MOVWF CCPR1L
    BANKSEL PORTB
    BSF PORTB,2
    BCF PORTB,3
    RETURN

PARO_EMERGENCIA
    CALL APAGAR_MOTOR
    BANKSEL INTCON
    BCF INTCON,INTF
    RETURN

;se llama cada 10 ms desde la ISR de Timer0.
CHEQUEAR_BOTONES
    BANKSEL PORTB
    BTFSS PORTB,0       
    GOTO BOTON_EMERG_ACTIVO

    BTFSC PORTB,1       
    RETURN

    BANKSEL FLAGS
    BSF FLAGS,0       
    RETURN               

BOTON_EMERG_ACTIVO
    CALL APAGAR_MOTOR    
    RETURN

CHEQUEAR_DISTANCIA
    BANKSEL DIST_CM
    MOVF UMBRAL_CM,W
    SUBWF DIST_CM,W      
    BTFSS STATUS,C
    GOTO DIST_APAGAR     
    BTFSC STATUS,Z
    GOTO DIST_APAGAR    

    BANKSEL FLAGS
    BTFSS FLAGS,0       
    RETURN                 
    CALL ENCENDER_MOTOR
    RETURN

DIST_APAGAR
    CALL APAGAR_MOTOR    
    RETURN

RUTINA_DISPLAY
    BANKSEL PORTE
    BCF PORTE,0
    BCF PORTE,1

    BANKSEL DISP_SEL
    BTFSS DISP_SEL,0
    GOTO SHOW_DECENAS

SHOW_UNIDADES
    BANKSEL UMBRAL_UNI
    MOVF UMBRAL_UNI,W
    CALL TABLA
    BANKSEL PORTD
    MOVWF PORTD
    BANKSEL PORTE
    BSF PORTE,1       
    BANKSEL DISP_SEL
    BCF DISP_SEL,0
    RETURN

SHOW_DECENAS
    BANKSEL UMBRAL_DEC
    MOVF UMBRAL_DEC,W
    CALL TABLA
    BANKSEL PORTD
    MOVWF PORTD
    BANKSEL PORTE
    BSF PORTE,0       
    BANKSEL DISP_SEL
    BSF DISP_SEL,0
    RETURN

;cada 10 llamadas (100 ms): leer ADC, medir sensor, comparar y enviar trama UART

RUTINA_CICLO
    INCF CICLO_CNT,F
    MOVLW .10
    SUBWF CICLO_CNT,W
    BTFSS STATUS,Z
    GOTO SOLO_RX

    CLRF CICLO_CNT
    CALL LEER_ADC           
    CALL MEDIR_SENSOR        
    CALL CHEQUEAR_DISTANCIA  
    CALL ENVIAR_TRAMA
    RETURN

SOLO_RX
    BTFSC PIR1, RCIF
    CALL ISR_UART_RX
    RETURN

LEER_ADC
    BANKSEL ADCON0
    BSF ADCON0,GO

ESPERAR_ADC
    BTFSC ADCON0,GO
    GOTO ESPERAR_ADC

    BANKSEL ADRESH
    MOVF ADRESH,W     
    BANKSEL ADC_RES
    MOVWF ADC_RES

    CALL MULT_ADC_X20    
    CALL DIV_PROD_255   

    BANKSEL QUOT
    MOVLW .5
    ADDWF QUOT,W
    BANKSEL UMBRAL_CM
    MOVWF UMBRAL_CM      
    
    BANKSEL BCD_TEMP
    MOVF UMBRAL_CM,W
    MOVWF BCD_TEMP        
    CLRF UMBRAL_DEC

;conviersión de un número binario a dígitos decimales
BCD_LOOP
    MOVLW .10
    SUBWF BCD_TEMP,W   
    BTFSS STATUS,C      
    GOTO BCD_FIN
    MOVWF BCD_TEMP        
    INCF UMBRAL_DEC,F
    GOTO BCD_LOOP

BCD_FIN
    MOVF BCD_TEMP, W
    MOVWF UMBRAL_UNI
    RETURN

MULT_ADC_X20
    BANKSEL PROD_H
    CLRF PROD_H
    CLRF PROD_L
    MOVLW .20
    MOVWF MULT_CNT
MULT_LOOP
    BANKSEL ADC_RES
    MOVF ADC_RES,W
    BANKSEL PROD_L
    ADDWF PROD_L,F
    BTFSC STATUS,C
    INCF PROD_H,F
    BANKSEL MULT_CNT
    DECFSZ MULT_CNT,F
    GOTO MULT_LOOP
    RETURN

DIV_PROD_255
    BANKSEL QUOT
    CLRF QUOT
DIV255_LOOP
    BANKSEL PROD_H
    MOVF PROD_H,W
    BTFSS STATUS,Z
    GOTO DIV_SUB         
    MOVLW .255
    BANKSEL PROD_L
    SUBWF PROD_L, W
    BTFSS STATUS, C
    GOTO DIV_DONE        
DIV_SUB
    MOVLW .255
    BANKSEL PROD_L
    SUBWF PROD_L,F
    BTFSS STATUS,C
    DECF PROD_H,F
    BANKSEL QUOT
    INCF QUOT,F
    GOTO DIV255_LOOP
DIV_DONE
    RETURN

MEDIR_SENSOR
    BANKSEL T1CON
    BCF T1CON,TMR1ON
    BANKSEL TMR1H
    CLRF TMR1H
    CLRF TMR1L
    BANKSEL PIR1
    BCF PIR1,TMR1IF

    BANKSEL PORTC
    BSF PORTC,0        ;TRIG alto
    MOVLW .7
    MOVWF CONT_DELAY
    
DELAY_TRIG
    DECFSZ CONT_DELAY,F
    GOTO DELAY_TRIG
    BCF PORTC,0        ;TRIG bajo

    MOVLW .5
    MOVWF CONT_HI
    MOVLW .200
    MOVWF CONT_DELAY

ESPERAR_ECHO_ALTO
    BANKSEL PORTC
    BTFSC PORTC,1
    GOTO ECHO_HIGH
    BANKSEL CONT_DELAY
    DECFSZ CONT_DELAY, F
    GOTO ESPERAR_ECHO_ALTO
    DECFSZ CONT_HI, F
    GOTO ESPERAR_ECHO_ALTO_R
    BANKSEL DIST_CM
    CLRF DIST_CM
    RETURN

ESPERAR_ECHO_ALTO_R
    MOVLW .200
    MOVWF CONT_DELAY
    GOTO ESPERAR_ECHO_ALTO

ECHO_HIGH
    BANKSEL PIR1
    BCF PIR1,TMR1IF
    BANKSEL T1CON
    BSF T1CON,TMR1ON

ESPERAR_ECHO_BAJO
    BANKSEL PORTC
    BTFSS PORTC,1
    GOTO ECHO_LOW
    BANKSEL PIR1
    BTFSC PIR1,TMR1IF
    GOTO ECHO_TIMEOUT
    GOTO ESPERAR_ECHO_BAJO

;DIST_CM=0
ECHO_TIMEOUT
    BANKSEL T1CON
    BCF T1CON,TMR1ON
    BANKSEL DIST_CM
    CLRF DIST_CM
    RETURN

;calcula la distancia
ECHO_LOW
    BANKSEL T1CON
    BCF T1CON,TMR1ON

    BANKSEL TMR1H
    MOVF TMR1H,W
    MOVWF TMR1_H
    MOVF TMR1L,W
    MOVWF TMR1_L

    BCF STATUS,C
    RLF TMR1_L,F    
    RLF TMR1_H,F
    BCF STATUS,C
    RLF TMR1_L,F    
    RLF TMR1_H,F
    BCF STATUS,C
    RLF TMR1_L,F    
    RLF TMR1_H,F

    MOVF TMR1L,W
    ADDWF TMR1_L,F
    BTFSC STATUS,C
    INCF TMR1_H,F
    MOVF TMR1H,W
    ADDWF TMR1_H,F

    BCF STATUS,C
    RRF TMR1_H,F
    MOVF TMR1_H,W
    BANKSEL DIST_CM
    MOVWF DIST_CM
    RETURN

ENVIAR_TRAMA
    MOVLW 'D'
    CALL TX_BYTE
    MOVLW ':'
    CALL TX_BYTE
    BANKSEL DIST_CM
    MOVF DIST_CM, W
    CALL BIN_TO_ASCII
    MOVF TX_DEC,W
    CALL TX_BYTE
    MOVF TX_UNI,W
    CALL TX_BYTE
    MOVLW 'c'
    CALL TX_BYTE
    MOVLW 'm'
    CALL TX_BYTE

    MOVLW ' '
    CALL TX_BYTE
    MOVLW 'U'
    CALL TX_BYTE
    MOVLW ':'
    CALL TX_BYTE
    BANKSEL UMBRAL_CM
    MOVF UMBRAL_CM,W
    CALL BIN_TO_ASCII
    MOVF TX_DEC,W
    CALL TX_BYTE
    MOVF TX_UNI,W
    CALL TX_BYTE
    MOVLW 'c'
    CALL TX_BYTE
    MOVLW 'm'
    CALL TX_BYTE

    MOVLW b'00001101'
    CALL TX_BYTE
    MOVLW b'00001010'
    CALL TX_BYTE
    RETURN

TX_BYTE
    MOVWF TEMP
    BANKSEL TXSTA
TX_WAIT
    BTFSS TXSTA,TRMT
    GOTO TX_WAIT
    BANKSEL TXREG
    MOVF TEMP,W
    MOVWF TXREG
    BANKSEL DIST_CM
    RETURN

;Convierte binario a ASCII
BIN_TO_ASCII
    MOVWF TEMP
    CLRF TX_DEC
BIN_DEC_LOOP
    MOVLW .10
    SUBWF TEMP,W
    BTFSS STATUS,C
    GOTO BIN_DEC_DONE
    MOVWF TEMP
    INCF TX_DEC,F
    GOTO BIN_DEC_LOOP
BIN_DEC_DONE
    MOVLW '0'
    ADDWF TEMP,W
    MOVWF TX_UNI
    MOVF TX_DEC,W
    ADDLW '0'
    MOVWF TX_DEC
    RETURN

ISR_UART_RX
    BANKSEL RCSTA
    BTFSS RCSTA,OERR
    GOTO CHECK_CMD
    BCF RCSTA,CREN
    BSF RCSTA,CREN
    BANKSEL DIST_CM
    RETURN

CHECK_CMD
    BANKSEL RCREG
    MOVF RCREG,W
    BANKSEL TEMP
    MOVWF TEMP

    MOVLW 'R'
    SUBWF TEMP,W
    BTFSC STATUS,Z
    GOTO CMD_REANUDAR

    MOVLW 'P'
    SUBWF TEMP,W
    BTFSC STATUS,Z
    GOTO CMD_PARAR
    RETURN

CMD_REANUDAR
    BANKSEL FLAGS
    BSF FLAGS,0
    RETURN

CMD_PARAR
    CALL APAGAR_MOTOR
    RETURN

    END